### ISSUE TITLE
Corruption is somewhat hosed in 2.5.0 and later

### ISSUE THREAD

**Issue by ghost** [nergantre/nightgamesmod#76]
If you get corrupted by Reyka, and then enter into combat with her, you'll eventually hit a NSEE and crash:

Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source)
	at nightgames.status.addiction.Corruption.getDrainAttr(Corruption.java:126)
	at nightgames.status.addiction.Corruption.noMoreAttrs(Corruption.java:122)
	at nightgames.status.addiction.Corruption.tick(Corruption.java:49)
	at nightgames.characters.Character.lambda$tick$7(Character.java:1116)
	at java.util.ArrayList.forEach(Unknown Source)
	at nightgames.characters.Character.tick(Character.java:1116)
	at nightgames.characters.Character.eot(Character.java:2126)
	at nightgames.characters.Player.eot(Player.java:716)
	at nightgames.combat.Combat.doEndOfTurnUpkeep(Combat.java:477)
	at nightgames.combat.Combat.turn(Combat.java:829)

**Comment by nergantre** [comment]
thanks for the report, this is fixed now
